jacobfholland/astro

astro/user/routes/user.py

https://jacobfholland.atlassian.net/browse/ACC-11
Adding REST specific endpoints.

ACC-11 [IMP] REST Specific Endpoints

---

astro/user/routes/user.py

https://jacobfholland.atlassian.net/browse/ACC-11
Adding get method parameter to routes get and get all.

ACC-11 [IMP] Defining Get Method For Get Routes

---

astro/__init__.py
astro/comment/routes/comment.py
astro/movie/routes/movie.py
astro/user/routes/user.py

https://jacobfholland.atlassian.net/browse/ACC-22
Adding URL prefix to blueprint for /api

ACC-22 [IMP] Add URL Prefix to Blueprint

---

pull_request_template.md

Create and add pull request template
None
[ACC-38]: https://jacobfholland.atlassian.net/browse/ACC-38?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-38 [ADD] Add Pull Request Template

---

astro/.env-sample
astro/__init__.py
astro/config/__init__.py
astro/config/models/__init__.py
astro/config/models/config.py

Create config class and environment, create app from config
None
[ACC-48]: https://jacobfholland.atlassian.net/browse/ACC-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-48 [ADD] Add Config Class And Environment

---

astro/__init__.py
astro/user/controllers/user.py
astro/user/models/user.py
astro/user/routes/user.py

Changed User1 to User
None
[ACC-12]: https://jacobfholland.atlassian.net/browse/ACC-12?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-12 [FIX] Changed User1 to User

---

astro/base/models/base.py

Add Keyword Arguments to Base functions
None
[ACC-59]: https://jacobfholland.atlassian.net/browse/ACC-59?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-59 [IMP] Add Keyword Arguments

---

astro/.env-sample
astro/__init__.py
astro/config/models/config.py
astro/user/controllers/user.py
astro/user/models/user.py
astro/user/routes/user.py

Add login, logout, and register.
None
[ACC-61]: https://jacobfholland.atlassian.net/browse/ACC-61?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-61 [Add] Add Login and Logout

---

astro/movie/routes/movie.py
astro/user/routes/user.py

Add login required to all appropiate routes
None
[ACC-69]: https://jacobfholland.atlassian.net/browse/ACC-69?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-69 [IMP] Add Login Required to All Routes

---

astro/user/controllers/user.py
astro/user/models/user.py

Move id related logic from user routes to user controller.
None
[ACC-74]: https://jacobfholland.atlassian.net/browse/ACC-74?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-74 [IMP] Abstract User Comment Logic

---

astro/.gitignore

Add migrations folder to gitignore
None
[ACC-93]: https://jacobfholland.atlassian.net/browse/ACC-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-93 [ADD] Add Migrations to gitignore

---

astro/__init__.py
astro/base/models/base.py
astro/genre/models/genre.py
astro/language/models/language.py
astro/movie/controllers/movie.py
astro/movie/models/movie.py
astro/person/controllers/person.py
astro/person/models/person.py
astro/tmdb/__init__.py
astro/tmdb/models/__init__.py
astro/tmdb/models/tmdb.py

Create TMDB Package
None
[ACC-95]: https://jacobfholland.atlassian.net/browse/ACC-95?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-95 [ADD] Create TMDB Package

---

astro/base/models/base.py
astro/genre/controllers/genre.py
astro/genre/models/genre.py
astro/genre/routes/genre.py
astro/genre/seeders/__init__.py
astro/genre/seeders/genre.py
astro/language/__init__.py
astro/language/controllers/language.py
astro/language/models/language.py
astro/language/routes/language.py
astro/language/seeders/__init__.py
astro/language/seeders/language.py

Create database seeders for languages and genres
None
[ACC-94]: https://jacobfholland.atlassian.net/browse/ACC-94?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-94 [ADD] Create Database Seeders

---

.vscode/route.code-snippets
astro/base/controllers/base.py
astro/base/models/base.py
astro/comment/models/comment.py
astro/comment/routes/comment.py
astro/movie/controllers/movie.py
astro/movie/models/movie.py
astro/movie/routes/movie.py
astro/person/controllers/person.py
astro/tmdb/models/tmdb.py
astro/user/controllers/user.py
astro/user/models/user.py
astro/user/routes/user.py

Create movie, user, and comment factories
None
[ACC-137]: https://jacobfholland.atlassian.net/browse/ACC-137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-137 [ADD] Create Factories

---

astro/base/controllers/base.py
astro/base/models/base.py
astro/base/models/crud.py
astro/user/controllers/user.py
astro/utils/functions/utils.py

Move request logic from models to controllers
None
[ACC-142]: https://jacobfholland.atlassian.net/browse/ACC-142?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-142 [REF] Move Request Logic from Models to Controllers

---

astro/__init__.py
astro/sandbox/__init__.py
astro/sandbox/controllers/__init__.py
astro/sandbox/controllers/sandbox.py
astro/sandbox/models/__init__.py
astro/sandbox/models/sandbox.py
astro/sandbox/routes/__init__.py
astro/sandbox/routes/sandbox.py

Create sandbox package
None
[ACC-147]: https://jacobfholland.atlassian.net/browse/ACC-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-147 [ADD] Create Sandbox Package

---

astro/.gitignore

Add sandbox to git ignore
None
[ACC-147]: https://jacobfholland.atlassian.net/browse/ACC-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-147 [FIX] Add Sandbox to Git Ignore

---

astro/modules/app/.gitignore

update gitignore
None
[ACC-159]: https://jacobfholland.atlassian.net/browse/ACC-159?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-159 [IMP] Update Gitignore

---

.gitignore
astro/modules/app/base/controllers/base.py
astro/modules/app/base/models/crud.py
astro/modules/app/user/controllers/user.py
astro/modules/app/user/models/__init__.py
astro/modules/app/user/models/comment.py
astro/modules/app/user/models/message.py
astro/modules/app/user/models/notification.py
astro/modules/app/user/models/user.py
astro/modules/app/user/routes/user.py

Create notification model
None
[ACC-129]: https://jacobfholland.atlassian.net/browse/ACC-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-129 [ADD] Create Notification Model

---

astro/modules/app/base/models/base.py

Take to_json and serialize out of base
None
[ACC-166]: https://jacobfholland.atlassian.net/browse/ACC-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-166 [IMP] Remove extraneous functions on Base

---

astro/modules/app/__init__.py
astro/modules/app/base/controllers/base.py
astro/modules/app/base/models/base.py
astro/modules/app/base/routes/base.py
astro/modules/app/language/__init__.py
astro/modules/app/language/models/__init__.py
astro/modules/app/language/models/language.py
astro/modules/app/language/seeders/__init__.py
astro/modules/app/language/seeders/language.py

Reintegrate Language package into new Base Route framework
None
[ACC-165]: https://jacobfholland.atlassian.net/browse/ACC-165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-165 [ADD] Reintegrate Language Package

---

astro/modules/app/user/models/user.py

Ensure passwords are hashed on user update and update all
None
[ACC-123]: https://jacobfholland.atlassian.net/browse/ACC-123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-123 [IMP] Hash Password On User Update

---

astro/modules/app/user/controllers/user.py
astro/modules/app/user/models/user.py
astro/modules/app/user/routes/user.py

Add delete all user comments functionality to user class
None
[ACC-63]: https://jacobfholland.atlassian.net/browse/ACC-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-63 [ADD]  Create "Delete User Comments"

---

astro/__init__.py
astro/modules/app/base/models/base.py
astro/modules/app/language/models/language.py
astro/modules/app/user/__init__.py
astro/modules/app/user/models/user.py
astro/modules/app/user/seeders/__init__.py
astro/modules/app/user/seeders/user.py

Did not build database seeders into createapp, but improved current database seeder functionality
None
[ACC-136]: https://jacobfholland.atlassian.net/browse/ACC-136?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-136 [IMP] Improve Database Seeders

---

astro/modules/app/__init__.py
astro/modules/app/user/routes/user.py
astro/modules/app/webhook/__init__.py
astro/modules/app/webhook/controllers/__init__.py
astro/modules/app/webhook/controllers/webhook.py
astro/modules/app/webhook/models/__init__.py
astro/modules/app/webhook/models/webhook.py
astro/modules/app/webhook/routes/__init__.py
astro/modules/app/webhook/routes/webhook.py

Create Webhook Package
None
[ACC-135]: https://jacobfholland.atlassian.net/browse/ACC-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-135 [ADD] Create Webhook Package

---

astro/modules/app/base/routes/base.py

Refactor CRUD RESTful endpoints to be dictated by the type of request
None
[ACC-167]: https://jacobfholland.atlassian.net/browse/ACC-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-167 [IMP] Refactor CRUD REST Endpoints

---

README.md

Create readme file
None
[ACC-116]: https://jacobfholland.atlassian.net/browse/ACC-116?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ACC-116 [ADD] Add Readme
